languageCode = "en-us"
title = "SICP Book Club!"
baseurl = "https://newswim.github.io/SICP-book-club/"
theme = "code-editor"
publishDir = "docs"
pygmentsuseclasses = false
# pygmentsstyle = "zenburn"
PygmentsCodeFences = true

[params]
    author = "John Doe"
    # required for `code-editor` theme
    locale = "en-US"
