languageCode = "en-us"
title = "SICP Book Club!"
baseurl = "http://www.sicpbook.club/"
theme = "code-editor"
publishDir = "docs"
pygmentsuseclasses = false
# pygmentsstyle = "zenburn"
PygmentsCodeFences = true

[params]
    author = "John Doe"
    # required for `code-editor` theme
    locale = "en-US"
