languageCode = "en-us"
title = "SICP Book Club!"
baseurl = "https://newswim.github.io/SICP-book-club/"

publishDir = "docs"

theme = "code-editor"

[params]
    author = "John Doe"
    # required for `code-editor` theme
    locale = "en-US"
