languageCode = "en-us"
title = "SICP Book Club!"
baseurl = "http://example.org/"

publishDir = "docs"

theme = "code-editor"

[params]
    author = "John Doe"
    # required for `code-editor` theme
    locale = "en-US"
