languageCode = "en-us"
title = "SICP Book Club!"
baseurl = "http://www.sicpbook.club/"
theme = "code-editor"
publishDir = "docs"
pygmentsuseclasses = false
PygmentsCodeFences = true
# pygmentsstyle = "zenburn"

[params]
    author = "Dan Minshew"
    # required for `code-editor` theme
    locale = "en-US"
